server:
    port: 8089
spring:
    profiles:
        active: dev
    datasource:
        url: jdbc:dm://127.0.0.1:5236/dm?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
        username: SYSDBA
        password: hxsdm123456
        driver-class-name: dm.jdbc.driver.DmDriver
        ConnectionTestQuery: SELECT 1
#    datasource:
#        url: jdbc:mysql://127.0.0.1:3306/employees?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
#        username: root
#        password: wzt3204885
#        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  # 指定sql映射文件位置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wzt.entity